#Parameters for Admittance Controller in assisted mode
final_vel_topic: /vel_cmd
human_wrench_topic: /human_wrench
falcon_wrench_topic: /falcon_wrench
update_params_service: /update_parameters
control_parameters:
  rate: 100
  mode: assisted_haptic
  mass: 8
  ldaming: 10
  inertia: 5
  adamping: 20
angular_vel_limit: 1
linear_vel_limit: 0.3
